import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';

export interface DbNotification {
  id: string;
  leadId: string | null;
  type: string;
  title: string;
  body: string | null;
  isRead: boolean;
  createdAt: string;
}

function rowToNotif(row: any): DbNotification {
  return {
    id: row.id,
    leadId: row.lead_id,
    type: row.type,
    title: row.title,
    body: row.body,
    isRead: row.is_read,
    createdAt: row.created_at,
  };
}

/** Poll `lc_notifications` (server-side alerts generated by pg_cron). */
export function useDbNotifications() {
  const { session } = useAuth();
  return useQuery({
    queryKey: ['db-notifications', session?.user.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('lc_notifications')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(50);
      if (error) throw error;
      return (data ?? []).map(rowToNotif);
    },
    enabled: !!session,
    refetchInterval: 120_000, // check every 2 minutes
  });
}

export function useMarkDbNotificationsRead() {
  const qc = useQueryClient();
  const { session } = useAuth();
  return useMutation({
    mutationFn: async (ids: string[]) => {
      if (!ids.length) return;
      const { error } = await supabase
        .from('lc_notifications')
        .update({ is_read: true })
        .in('id', ids);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ['db-notifications', session?.user.id] }),
  });
}

export function useMarkAllDbNotificationsRead() {
  const qc = useQueryClient();
  const { session } = useAuth();
  return useMutation({
    mutationFn: async () => {
      if (!session) return;
      const { error } = await supabase
        .from('lc_notifications')
        .update({ is_read: true })
        .eq('user_id', session.user.id)
        .eq('is_read', false);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ['db-notifications', session?.user.id] }),
  });
}
